clickbar/laravel-magellan

CHANGELOG.md
README.md
config/magellan.php
src/MagellanServiceProvider.php

We currently tried to convert bindings, that were geometries, to an SQL representation. This does not work, since bindings are passed as strings to the DB. Thus it cannot execute functions like ST_GeomFromEWKT in such a binding.
So to fix this issue we will for now remove our custom DB hook and let PHP bind our geometries as strings. So it will now implicitly use the string generator.
This method works for all generators and we might consider adding a custom stUpdate command in the future once we need more explicit control.

Remove DB hook to fix having sql in binding values

---

CHANGELOG.md
src/Database/PostgisFunctions/MagellanGeometryProcessingFunctions.php
src/Database/PostgisFunctions/MagellanMeasurementFunctions.php
src/Database/PostgisFunctions/MagellanTopologicalRelationshipFunctions.php

Some functions $geometryType parameter was still using the strings, instead of our new GeometryType enum. Thus PHP throws an error when using them.

Fix some expressions to use GeometryType enum for $geometryType

---

CHANGELOG.md
src/Database/Builder/BuilderUtils.php
src/Rules/GeometryGeojsonRule.php

These functions now require a parameter, the grammar. To avoid builing special version specific code, we are
utilizing the grammar's own wrap() function
which calls getValue on the expression for us.
So this method works for both Laravel 9 & 10.

Fix Laravel 10 expression getValue calls

---

CHANGELOG.md
src/Database/Builder/BuilderMacros.php

Previously the Builder Macro `toGeojsonFeatureCollection` returned `{"type" : "FeatureCollection", "features" : null}` if there are zero database rows.
Now it properly returns `{"type" : "FeatureCollection", "features" : []}`

Fixed generation of invalid FeatureCollection in case of zero rows

---

CHANGELOG.md
src/Database/Builder/BuilderUtils.php

Since Laravel 10 Expressions are not stringable anymore.
Therefore, using a DB::raw, that created an expression breaks the transformation step.

Fixed missing handling of expressions in GeoParam

---

CHANGELOG.md
src/Http/Requests/TransformsGeojsonGeometry.php
tests/Extra/GeometryFormRequest.php
tests/Http/Requests/TransformsGeojsonGeometryTest.php

This fixes exceptions thrown when using the TransformsGeojsonGeometry trait with nullable fields.
Additionally, a test case for this problem was added and the createRequest helper function was simplified.
Fixes #37

fix: Handling null in TransformsGeojsonGeometry

---

src/IO/Parser/Geojson/GeojsonParser.php

Fix the typo in the protected function named `parseGeomeryCollection`.

Fix typo in GeojsonParser.php

---

.github/workflows/check-styling.yml

We require the check to be successful, but we do not run it on pull requests.

ci: Rename and run check styling on prs too

---

CHANGELOG.md
src/Database/Builder/BuilderMacros.php

The generation code has some issues with imported class names in docblocks. It does not resolve those properly and thus leads to incorrect annotations. This was mitigated by transforming all current macro annotations to use the fully qualified class names
See https://github.com/barryvdh/laravel-ide-helper/pull/953
Before this PR:
```php
/**
*
*
* @param array|string|\MagellanBaseExpression $groups
* @return static
* @see \Clickbar\Magellan\Database\Builder\BuilderMacros::stGroupBy()
* @static
*/
public static function stGroupBy(...$groups)
{
return \Illuminate\Database\Query\Builder::stGroupBy(...$groups);
}
```
After:
```php
/**
*
*
* @param array|string|\Clickbar\Magellan\Database\MagellanExpressions\MagellanBaseExpression $groups
* @return static
* @see …
```

fix(docblocks): Mitigate issue in ide-helper docblock parsing 

---

CHANGELOG.md
src/Data/Geometries/Point.php

I ran into this issue by converting a LineString object via the WKTGenerator to a wkt string. Even though every point has a z value  the value is not included in the resulting converted wkt string.
Before the converting is done I am setting new altitude / z values for each point via the setAltitude function. I saw that this function doesn't call the updateDimension function like setZ function would do. When I use the setZ function everything works fine. So I changed the setAltitude function to call the internal setZ function and made this logical change to setLatitude and setLongitude as well.
I hope I have done everything right because this is my first pull request.
Please let me know if I made any mistakes.

Update Point.php to update dimension when using setAltitude

---

CHANGELOG.md
src/Database/Eloquent/HasPostgisColumns.php

This fix #87 by decreasing the code override from the Eloquent Model class.
- Instead of overriding the whole `performInsert` method, we now override the `getAttributesForInsert` method which only cares about getting the attributes to be inserted into the database.
- Instead of overriding the whole `performUpdate` method, we now override the `getDirtyForUpdate` method which only cares about getting the modified attributes to be updated into the database.

Overrides getAttributesForInsert & getDirtyForUpdate instead of performInsert & performUpdate to 

---

CHANGELOG.md
src/Database/Builder/BuilderUtils.php

The schema was never added to the ST functions on the first level. This is usually no problem, because people use the public schema anyway. Though for correctness and to properly support changing the schema we fixed this.

fix(builder): add missing schema prefix to ST SQL

---

CHANGELOG.md
src/Database/PostgisFunctions/MagellanSpatialReferenceSystemFunctions.php

When using numeric values for the SRID in functions like `ST_Transform`, the query will throw an error that it cannot parse the SRID projection.
This seems to be caused by the PDO driver, which internally always converts parameters to strings.
See https://stackoverflow.com/questions/66625661/cannot-bind-value-as-int-with-pdo-pgsql-driver
We now append a `::int` cast to numeric SRID parameters, so they work as expected again.
For Closures and Expressions, the developer needs to take care of this. We added a note to make them aware of this behavior.

fix(builder): numeric SRID SQL queries

---

CHANGELOG.md
src/Database/PostgisFunctions/MagellanOtherFormatFunctions.php
src/Database/PostgisFunctions/ST.php
src/Enums/GeojsonOutputOption.php

We added the `ST_AsGeoJSON` function to the `ST` builder class.
This can come in handy when building queries for the frontend.

feat(ST): add asGeoJson function

---

CHANGELOG.md
README.md
composer.lock
phpunit.xml.dist
src/Cast/GeometryCast.php
src/Data/Geometries/Geometry.php
src/Data/Geometries/GeometryCollection.php
src/Data/Geometries/LineString.php
src/Data/Geometries/MultiLineString.php
src/Data/Geometries/MultiPoint.php
src/Data/Geometries/MultiPolygon.php
src/Data/Geometries/Point.php
src/Data/Geometries/Polygon.php
src/Database/Builder/EloquentBuilderMacros.php
tests/Models/Geometry.php
tests/Models/GeometryTypesTest.php
tests/Models/Location.php
tests/Models/SpatialQueriesTest.php

Let's write the description by hand again :D
@saibotk  and I realized, that a lot of the time people will use point geometries in their database tables. 
When they use the GeometryCast, an actual `Point` object will be returned, but the type will be the abstract base class `Geometry`. 
So whenever someone use phpstan or want a better auto completion, they will have to write 
```php
/** @var Point $point */
```
what is quite annoying and not properly typ safe. 
So we decided to add a cast for every supported geometry type. 
So in our first approach we came up with something like:
- `PointCast`
- `MultiPointCast`
- `LineStringCast`
- ...
After some consideration we came up with only the specific geometry class as caster.
Just like someone would do it with an enum.
So this PR adds the …

[2.x] Specific Casts

---

src/Database/PostgisFunctions/MagellanMeasurementFunctions.php

ST_DistanceSphere does only accept geometry params.

Fix accidentally renamed params

---

CHANGELOG.md
src/Data/Geometries/GeometryHelper.php
tests/Generator/WKT/WKTGeneratorPointTest.php

We missed the "." here and thus PHP formatted numbers with the default precision of 6 and prefixed it with whitespaces.
See PHP docs: https://www.php.net/manual/en/function.sprintf.php
This has been addressed by using the `json_encode` function to print the
float. This function uses PHP's `serialize_precision` instead, which
by default uses a similar algorithm to the one PostGIS uses for
printing out the float in a minimal representation and also
allows to print out at the maximum precision, as long as the
user did not change the serialization precision config.
Thanks @ronnypolloqueri for reporting this. (ref #72)

fix(geometries): Fix missing precision in WKT coordinates

---

CHANGELOG.md
src/Data/Geometries/GeometryHelper.php
tests/Generator/WKT/WKTGeneratorPointTest.php

We missed the "." here and thus PHP formatted numbers with the default precision of 6 and prefixed it with whitespaces. See PHP docs: https://www.php.net/manual/en/function.sprintf.php
This has been addressed by using the `json_encode` function to print the float. This function uses PHP's `serialize_precision` instead, which by default uses a similar algorithm to the one PostGIS uses for printing out the float in a minimal representation and also allows to print out at the maximum precision, as long as the user did not change the serialization precision config.
Thanks @ronnypolloqueri for reporting this.
(cherry picked from commit 3c364e39e01b80cae940a81a12315af15a34610a)

[1.x] Backport: Fix missing precision in WKT coordinates

---

CHANGELOG.md
README.md
src/Cast/BBoxCast.php
src/Data/Boxes/Box.php
src/Data/Boxes/Box2D.php
src/Data/Boxes/Box3D.php
src/Database/Builder/EloquentBuilderMacros.php
tests/Models/SpatialQueriesTest.php

Implemented a `fromString` method for `Box` classes to parse strings and create instances.
Added Castable to all Box classes and refactored `BBoxCast` to be generic. Every Box instance can now be used in casts in the same way as all geometries can be used.

feat!(box): add castable to boxes & fromString

---

CHANGELOG.md
src/Data/Boxes/Box2D.php
src/Data/Boxes/Box3D.php
tests/Data/BoxesTest.php

The Box classes previously built the string and the floats where cast to string. This looses some precision, because the PHP precision is used instead of the serialization precision.
We now also use the `GeometryHelper` function here, in the same way that we used it in the WKT generator.

fix(box): use maximum precision in toString

---

CHANGELOG.md
src/Data/Boxes/Box.php
src/Data/Boxes/Box2D.php
src/Data/Boxes/Box3D.php

Box classes now implement `JsonSerializable` and serialize to float arrays, which is a common format in frontend libraries.
Fixes #36

[2.x] add JsonSerializable to Box classes

---

CHANGELOG.md
README.md
src/Database/MagellanExpressions/MagellanBaseExpression.php
tests/Models/SpatialQueriesTest.php

This PR adds the helper function `->as(string)` on MagellanBaseExpression, that can wrap the expression into an Aliased.
Most of the changes are in Readme and tests :D

[2.x] As helper on MagellanBaseExpression

---

CHANGELOG.md
src/Cast/BBoxCast.php
src/Data/Boxes/Box.php
src/Data/Boxes/Box2D.php
src/Data/Boxes/Box3D.php
tests/Data/BoxesTest.php

This properly adds `Stringable` to `Box` classes, so they can be printed etc. We still keep an extra function to create the string, because it concerns the database and should not be tied to the method that converts the object to a string in general.
Fix CB-25

[2.x] Box: Implement Stringable interface

---

UPGRADING.md

[2.x] Upgrading Guide

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/config.yml

The security policy option is already shown through GitHub. 
Additionally, the bug template needs to exist to be able to create an issue. 
The link is automatically shown.
The template was taken from https://github.com/spatie/package-skeleton-laravel/blob/9ceafb99c72fe1ebca763c054667d0f102933675/.github/ISSUE_TEMPLATE/bug.yml

chore(github): add bug template & cleanup issue config
